name: Package and Release

# Run on new tags
on:
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # secret is automatically provided to the workflow

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone
        uses: actions/checkout@v1  # note: checkout@v2 breaks git history, so generating a changelog and
                                   # file naming for non-tagged builds will not work properly

      - name: BigWigs Packager
        uses: BigWigsMods/packager@v2
        with:
          args: -a kaNewXK2 -p 361123 -w 0
